workflows:
  default-workflow:
    name: Flujo de trabajo predeterminado
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events: []
    scripts:
      - name: Obtener dependencias y autogenerar archivos de entorno iOS
        script: |
          flutter clean
          flutter pub get
          
          # TRUCO: Creamos la carpeta y un archivo vacío temporal en la Mac de Codemagic
          mkdir -p ios/Flutter
          touch ios/Flutter/flutter_export_environment.sh
          touch ios/Flutter/generated_xcode_build_settings.mgmt
          
          # Ahora Flutter actualizará estos archivos con las rutas de macOS sin que CocoaPods proteste
          flutter build ios --config-only --debug --no-codesign
      - name: Instalar dependencias nativas (Pod install)
        script: |
          export COCOAPODS_DISABLE_STATS=true
          cd ios
          pod repo remove master || true
          pod install --repo-update
          cd ..
      - name: Compilar Flutter para iOS (Debug)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
