platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  # Aquí se inyectan dinámicamente los plugins de Flutter en la compilación remota
  pod_helpers_path = File.join(File.dirname(__FILE__), '.symlinks', 'plugins', 'flutter_plugin_loader', 'ios', 'podhelper.rb')
  if File.exist?(pod_helpers_path)
    eval(File.read(pod_helpers_path), binding, pod_helpers_path)
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Forzamos a que todos los pods de Google MLKit y tu app usen iOS 13
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
